name: juin_dart
description: Simple compiler for educational purposes
version: 0.8.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  petitparser:
  
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
